#include "model.h"
#include "board.h"
#include <lvgl.h>
// Pinned LVGL 9.3 test-only access to the actual keyboard button rectangles.
#include <src/widgets/buttonmatrix/lv_buttonmatrix_private.h>
#include <fixture.h>
#include <printer_fixture.h>
#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <filesystem>
void homelabPreviewInit(Snapshot*,NetworkState*);
void homelabPreviewShow(uint8_t);
void homelabPreviewScroll(int);
void homelabPreviewTheme(bool);
void homelabPreviewGuest(int);
void homelabPreviewRefresh();
void homelabPreviewPoll();
uint8_t homelabPreviewHistoryCount();
uint8_t homelabPreviewPage();
bool homelabPreviewLightTheme();
bool homelabPreviewBusy();
bool homelabPreviewAutoRotate();
bool homelabPreviewIdleDim();
uint8_t homelabPreviewFilter();
uint8_t homelabPreviewBrightness();
int homelabPreviewHeaderHeight();
uint32_t nativeClock=1000;uint32_t millis(){return nativeClock;}
Snapshot *publishedSnapshot=nullptr;SemaphoreHandle_t dataMutex=nullptr;NetworkState networkState;volatile bool requestSetup=false;
void boardHoldPower(){}void boardInit(){}void boardBacklight(uint8_t){}void boardLvglInit(){}void startNetwork(){}bool readSnapshot(Snapshot&out,NetworkState&state){if(!publishedSnapshot)return false;out=*publishedSnapshot;state=networkState;return true;}void makeDemo(Snapshot&s){loadFixture(s,networkState);}
bool requestNodeSelection(const char*id){if(!publishedSnapshot||!validNodeId(id))return false;for(int i=0;i<publishedSnapshot->nNodes;i++)if(!strcmp(id,publishedSnapshot->nodes[i].id)){clearForNode(*publishedSnapshot,publishedSnapshot->nodes[i]);networkState.loading=true;strlcpy(networkState.message,"Loading selected node",sizeof(networkState.message));networkState.revision++;return true;}return false;}
#include "native_management.h"
extern "C" void*homelab_lvgl_pool(size_t n){static void*p=calloc(1,n);return p;}
lv_indev_data_t sample{};lv_indev_t*pointer=nullptr;lv_display_t*display=nullptr;
constexpr int width=HOMELAB_VIEWPORT_WIDTH,height=HOMELAB_VIEWPORT_HEIGHT;
int headerHeight=0;
alignas(4) uint8_t drawBuffer[width*24*2];
uint16_t pixels[width*height];
void flush(lv_display_t*d,const lv_area_t*a,uint8_t*p){auto*s=(uint16_t*)p;int w=a->x2-a->x1+1;for(int y=a->y1;y<=a->y2;y++)for(int x=a->x1;x<=a->x2;x++)pixels[y*width+x]=s[(y-a->y1)*w+x-a->x1];lv_display_flush_ready(d);}
void input(lv_indev_t*,lv_indev_data_t*d){*d=sample;noteTouch(sample.state==LV_INDEV_STATE_PRESSED);if(consumeWakeTouch)d->state=LV_INDEV_STATE_RELEASED;}
void point(int x,int y,bool down){sample.point.x=x;sample.point.y=y;sample.state=down?LV_INDEV_STATE_PRESSED:LV_INDEV_STATE_RELEASED;nativeClock+=35;lv_indev_read(pointer);lv_timer_handler();lv_refr_now(display);}
void settle(){for(int i=0;i<70;i++){nativeClock+=30;lv_timer_handler();}lv_refr_now(display);}
void tap(int x,int y){point(x,y,true);point(x+2,y+1,true);point(x+2,y+1,false);settle();}
void dumpLabels(lv_obj_t*o);
void expect(bool ok,const char*name){if(!ok){fprintf(stderr,"FAIL: %s (page=%u)\n",name,unsigned(homelabPreviewPage()));dumpLabels(lv_screen_active());exit(1);}printf("PASS: %s\n",name);}
lv_obj_t*findText(lv_obj_t*o,const char*value,bool exact=false){if(lv_obj_check_type(o,&lv_label_class)){const char*t=lv_label_get_text(o);if(exact?!strcmp(t,value):strstr(t,value)!=nullptr)return o;}for(uint32_t i=0;i<lv_obj_get_child_count(o);i++)if(auto*found=findText(lv_obj_get_child(o,i),value,exact))return found;return nullptr;}
lv_obj_t*findClass(lv_obj_t*o,const lv_obj_class_t*cls){if(lv_obj_check_type(o,cls))return o;for(uint32_t i=0;i<lv_obj_get_child_count(o);i++)if(auto*found=findClass(lv_obj_get_child(o,i),cls))return found;return nullptr;}
void dumpLabels(lv_obj_t*o){if(lv_obj_check_type(o,&lv_label_class))fprintf(stderr,"LABEL: %s\n",lv_label_get_text(o));for(uint32_t i=0;i<lv_obj_get_child_count(o);i++)dumpLabels(lv_obj_get_child(o,i));}
lv_point_t objectPoint(lv_obj_t*o,bool scrollTo=true){
 if(!o){fprintf(stderr,"FAIL: control missing (page %u)\n",unsigned(homelabPreviewPage()));exit(1);}
 if(scrollTo)lv_obj_scroll_to_view_recursive(o,LV_ANIM_OFF);lv_obj_update_layout(lv_screen_active());lv_refr_now(display);lv_area_t a;lv_obj_get_coords(o,&a);
 lv_point_t p={(a.x1+a.x2)/2,(a.y1+a.y2)/2};
 if(p.x<0||p.x>=width||p.y<0||p.y>=height){fprintf(stderr,"FAIL: control outside viewport (%d,%d) page %u\n",int(p.x),int(p.y),unsigned(homelabPreviewPage()));exit(1);}return p;
}
lv_point_t buttonPoint(const char*text,bool exact=true){lv_obj_update_layout(lv_screen_active());auto*l=findText(lv_screen_active(),text,exact);if(!l){fprintf(stderr,"FAIL: button not found: %s (page %u)\n",text,unsigned(homelabPreviewPage()));dumpLabels(lv_screen_active());exit(1);}return objectPoint(lv_obj_get_parent(l));}
void tapButton(const char*text,bool exact=true){auto p=buttonPoint(text,exact);tap(p.x,p.y);}
void tapTab(int index){tap(width*(2*index+1)/8,height-20);}
void tapBack(){tapButton(LV_SYMBOL_LEFT);}
lv_point_t switchPoint(const char*text){auto*l=findText(lv_screen_active(),text,true);return objectPoint(l?findClass(lv_obj_get_parent(l),&lv_switch_class):nullptr);}
void dragReturning(lv_point_t p,int travel=22){point(p.x,p.y,true);point(std::min(width-1,int(p.x)+travel),p.y,true);point(p.x,p.y,true);point(p.x,p.y,false);settle();}
lv_point_t keyboardPoint(const char*text){lv_obj_update_layout(lv_screen_active());auto*o=findClass(lv_screen_active(),&lv_keyboard_class);if(!o){fprintf(stderr,"FAIL: keyboard missing\n");exit(1);}auto*m=reinterpret_cast<lv_buttonmatrix_t*>(o);lv_area_t a;lv_obj_get_coords(o,&a);for(uint32_t i=0;i<m->btn_cnt;i++){const char*t=lv_buttonmatrix_get_button_text(o,i);if(t&&!strcmp(t,text)){auto&r=m->button_areas[i];return {a.x1+(r.x1+r.x2)/2,a.y1+(r.y1+r.y2)/2};}}fprintf(stderr,"FAIL: keyboard key not found: %s\n",text);exit(1);}
void tapKey(const char*text){auto p=keyboardPoint(text);tap(p.x,p.y);}
bool horizontalButtonVisible(const char*text){lv_obj_update_layout(lv_screen_active());auto*l=findText(lv_screen_active(),text,true);if(!l)return false;auto*button=lv_obj_get_parent(l);lv_area_t b,p;lv_obj_get_coords(button,&b);lv_obj_get_coords(lv_obj_get_parent(button),&p);return b.x1>=p.x1&&b.x2<=p.x2;}
bool controlsOverlap(lv_obj_t*a,lv_obj_t*b){lv_area_t x,y;lv_obj_get_coords(a,&x);lv_obj_get_coords(b,&y);return x.x1<=y.x2&&y.x1<=x.x2&&x.y1<=y.y2&&y.y1<=x.y2;}
bool contentLabelsClearTabs(lv_obj_t*o){if(lv_obj_check_type(o,&lv_label_class)){lv_area_t a;lv_obj_get_coords(o,&a);if(a.y1<headerHeight||a.y2>height-43)return false;}for(uint32_t i=0;i<lv_obj_get_child_count(o);i++)if(!contentLabelsClearTabs(lv_obj_get_child(o,i)))return false;return true;}
void screenshot(const char *path){lv_refr_now(display);std::ofstream out(path,std::ios::binary);out<<"P6\n"<<width<<" "<<height<<"\n255\n";for(auto v:pixels){unsigned char b[3]={static_cast<unsigned char>(((v>>11)&31)*255/31),static_cast<unsigned char>(((v>>5)&63)*255/63),static_cast<unsigned char>((v&31)*255/31)};out.write((char*)b,3);}}
int main(int argc,char**argv){
 std::filesystem::path output=argc>1?argv[1]:"/tmp/homelab-gesture-qa";std::filesystem::create_directories(output);
 static Snapshot s;loadFixture(s,networkState);printf("fixture_sha256=%s\n",fixtureFingerprint());printf("viewport=%dx%d rotation=%d\n",width,height,HOMELAB_ROTATION);expect(s.nGpus==2,"gesture fixture contains exactly two GPUs");s.generated=time(nullptr);s.received=nativeClock;
 lv_init();lv_tick_set_cb(millis);display=lv_display_create(width,height);lv_display_set_color_format(display,LV_COLOR_FORMAT_RGB565);lv_display_set_flush_cb(display,flush);lv_display_set_buffers(display,drawBuffer,nullptr,sizeof(drawBuffer),LV_DISPLAY_RENDER_MODE_PARTIAL);
 publishedSnapshot=&s;homelabPreviewInit(&s,&networkState);pointer=lv_indev_create();lv_indev_set_type(pointer,LV_INDEV_TYPE_POINTER);lv_indev_set_read_cb(pointer,input);lv_indev_set_scroll_limit(pointer,8);
 expect(homelabPreviewPage()==19,"new session opens the all-nodes overview");homelabPreviewShow(0);settle();
 headerHeight=homelabPreviewHeaderHeight();lv_obj_update_layout(lv_screen_active());
 auto*nodeNameLabel=findText(lv_screen_active(),s.node.name,true);auto*nodeControl=lv_obj_get_parent(nodeNameLabel);auto*stateControl=lv_obj_get_parent(findText(lv_screen_active(),"DEMO",true));auto*gearControl=lv_obj_get_parent(findText(lv_screen_active(),LV_SYMBOL_SETTINGS,true));
 expect(!controlsOverlap(nodeControl,stateControl)&&!controlsOverlap(nodeControl,gearControl)&&!controlsOverlap(stateControl,gearControl),"node selector, status and Settings have separate hit areas");
 lv_area_t nodeBounds,stateBounds;lv_obj_get_coords(nodeControl,&nodeBounds);lv_obj_get_coords(stateControl,&stateBounds);expect(std::abs((nodeBounds.y1+nodeBounds.y2)-(stateBounds.y1+stateBounds.y2))<=2,"node selector and status badge align on the same row");
 // Retain the rendered label: LVGL's dot mode can temporarily shorten its text.
 char originalName[sizeof(s.node.name)];strlcpy(originalName,s.node.name,sizeof(originalName));strlcpy(s.node.name,"Example printer",sizeof(s.node.name));homelabPreviewRefresh();lv_obj_update_layout(lv_screen_active());lv_point_t nameSize;lv_text_get_size(&nameSize,s.node.name,lv_obj_get_style_text_font(nodeNameLabel,0),0,0,LV_COORD_MAX,LV_TEXT_FLAG_NONE);expect(!HOMELAB_IS_PORTRAIT||nameSize.x<=lv_obj_get_width(nodeNameLabel),"portrait selector shows a normal printer name without ellipsis");strlcpy(s.node.name,originalName,sizeof(s.node.name));homelabPreviewRefresh();
 for(int phase=0;phase<4;phase++){nativeClock=(nativeClock/24000+1)*24000+phase*6000+1000;s.received=nativeClock;s.generated=time(nullptr);homelabPreviewShow(0);settle();auto*cpu=findText(lv_screen_active(),"CPU",true);expect(contentLabelsClearTabs(lv_obj_get_parent(lv_obj_get_parent(cpu))),"overview summary text stays clear of the bottom tabs");screenshot((output/("overview-phase-"+std::to_string(phase)+".ppm")).string().c_str());}
 homelabPreviewShow(0);settle();
 expect(homelabPreviewLightTheme(),"new session defaults to white");
 expect(!homelabPreviewIdleDim(),"desk display stays bright by default");
 homelabPreviewShow(1);homelabPreviewScroll(0);settle();
 point(100,headerHeight+46,true);expect(homelabPreviewBusy(),"pressed pointer suppresses refresh");point(100,headerHeight+34,true);point(100,headerHeight+20,true);point(100,headerHeight+4,true);point(100,headerHeight+4,false);expect(homelabPreviewPage()==1,"swipe across guest rows does not navigate");settle();
 homelabPreviewShow(1);homelabPreviewScroll(0);settle();tapButton(s.guests[0].name);expect(homelabPreviewPage()==4,"deliberate guest tap opens detail");tapBack();expect(homelabPreviewPage()==1,"back toolbar tap works");
 auto guestStart=buttonPoint(s.guests[0].name);point(guestStart.x,guestStart.y,true);point(guestStart.x,guestStart.y+35,true);point(guestStart.x,std::min(height-41,int(guestStart.y)+85),true);point(guestStart.x,height-20,true);point(guestStart.x,height-20,false);expect(homelabPreviewPage()==1,"swipe ending over bottom tab stays on guest page");settle();
 homelabPreviewShow(0);settle();dragReturning(buttonPoint(LV_SYMBOL_SETTINGS),15);expect(homelabPreviewPage()==0,"drag returning to start is not a gear tap");tapButton(LV_SYMBOL_SETTINGS);expect(homelabPreviewPage()==7,"deliberate gear tap opens settings");
 homelabPreviewScroll(0);settle();tapButton("Dark");expect(!homelabPreviewLightTheme(),"Dark choice changes palette through actual tap");screenshot((output/"dark-settings.ppm").string().c_str());
 tapButton("White");expect(homelabPreviewLightTheme(),"White choice restores palette through actual tap");screenshot((output/"white-settings.ppm").string().c_str());
 homelabPreviewScroll(0);settle();bool before=homelabPreviewAutoRotate();auto rotate=switchPoint("Rotate pages every 15s");dragReturning(rotate);expect(homelabPreviewAutoRotate()==before,"drag over switch does not toggle auto rotation");tap(rotate.x,rotate.y);expect(homelabPreviewAutoRotate()!=before,"deliberate switch tap toggles auto rotation");
 homelabPreviewScroll(0);settle();uint8_t brightness=homelabPreviewBrightness();auto*slider=findClass(lv_screen_active(),&lv_slider_class);objectPoint(slider);lv_area_t sliderArea;lv_obj_get_coords(slider,&sliderArea);int sliderY=(sliderArea.y1+sliderArea.y2)/2,sliderEnd=sliderArea.x1+lv_area_get_width(&sliderArea)/4;point(sliderArea.x1+lv_area_get_width(&sliderArea)*3/4,sliderY,true);point(sliderEnd,sliderY,true);point(sliderEnd,sliderY,false);expect(homelabPreviewBrightness()!=brightness,"horizontal brightness drag still works");
 auto dim=switchPoint("Dim after 2 min");dragReturning(dim);expect(!homelabPreviewIdleDim(),"drag over optional dim switch does not toggle it");tap(dim.x,dim.y);expect(homelabPreviewIdleDim(),"deliberate dim-switch tap enables optional dimming");tap(dim.x,dim.y);expect(!homelabPreviewIdleDim(),"deliberate dim-switch tap restores always-bright mode");
 tapTab(3);expect(homelabPreviewPage()==3,"bottom sensor tab deliberate tap works");
 auto chip=buttonPoint("Fans");point(chip.x,chip.y,true);point(chip.x+40,chip.y,true);point(chip.x+80,chip.y,true);point(chip.x,chip.y,true);point(chip.x,chip.y,false);expect(homelabPreviewFilter()==1,"drag across sensor chips does not select a category");settle();
 tapButton("Fans");expect(homelabPreviewFilter()==2,"Fans chip deliberate tap works");tapButton("Volts");expect(homelabPreviewFilter()==3,"Volts chip deliberate tap works");tapButton("Power");expect(homelabPreviewFilter()==4,"Power sensor chip deliberate tap works");expect(horizontalButtonVisible("Power"),"selected Power chip remains fully visible after list rebuild");expect(findText(lv_screen_active(),"CPU package")&&findText(lv_screen_active(),"NVIDIA GPU")&&findText(lv_screen_active(),"93.4 W")&&findText(lv_screen_active(),"25.1 W"),"Power filter displays measured CPU and GPU watts");tapButton("Amps");expect(homelabPreviewFilter()==5,"Amps chip deliberate tap works");expect(horizontalButtonVisible("Amps"),"selected Amps chip remains fully visible after list rebuild");expect(findText(lv_screen_active(),"No current sensors reported")&&findText(lv_screen_active(),"do not expose amperage")&&!findText(lv_screen_active(),"Hardware sensors unavailable"),"healthy empty Amps explains missing current measurements without a source error");screenshot((output/"amps-healthy.ppm").string().c_str());
 int sourceIndex=-1;for(int i=0;i<s.nSources;i++)if(!strcmp(s.sources[i].name,"sensors"))sourceIndex=i;expect(sourceIndex>=0,"sensor source exists in pointer fixture");s.sources[sourceIndex].ok=false;homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),"Hardware sensors unavailable")&&findText(lv_screen_active(),"Open Health"),"failed sensor source has distinct collection-error advice");screenshot((output/"amps-source-failure.ppm").string().c_str());s.sources[sourceIndex].ok=true;homelabPreviewRefresh();settle();
 homelabPreviewTheme(false);screenshot((output/"dark-amps-healthy.ppm").string().c_str());homelabPreviewTheme(true);settle();tapButton("All");expect(homelabPreviewFilter()==0,"All sensor chip deliberate tap works");tapButton("Temp");expect(homelabPreviewFilter()==1,"Temp chip deliberate tap restores temperatures");
 tap(width-31,headerHeight+42);expect(homelabPreviewPage()==5,"sensor power shortcut opens CPU detail");tapBack();expect(homelabPreviewPage()==3,"CPU detail returns to its sensor origin");
 tapTab(0);expect(homelabPreviewPage()==0,"overview tab deliberate tap works");tapButton("CPU");expect(homelabPreviewPage()==5,"deliberate CPU card tap opens CPU detail");tapBack();expect(homelabPreviewPage()==0,"CPU card detail returns to overview");
 tapButton("MEMORY");expect(homelabPreviewPage()==10,"deliberate RAM card tap opens memory detail");tapBack();expect(homelabPreviewPage()==0,"memory detail returns to overview");
 tapTab(1);expect(homelabPreviewPage()==1,"guest tab deliberate tap works");tapButton("DEMO");expect(homelabPreviewPage()==6,"connection badge opens health");tapBack();expect(homelabPreviewPage()==1,"health returns to its guest origin");
 homelabPreviewShow(0);settle();tapButton("CPU");expect(homelabPreviewPage()==5,"CPU shortcut start is actual CPU detail");tapButton("GPUs • 2 devices  >");expect(homelabPreviewPage()==11,"CPU GPU shortcut opens GPU list");
 auto gpuStart=buttonPoint(s.gpus[0].name);point(gpuStart.x,gpuStart.y,true);point(gpuStart.x,gpuStart.y-18,true);point(gpuStart.x,headerHeight+4,true);point(gpuStart.x,headerHeight+4,false);expect(homelabPreviewPage()==11,"GPU list swipe does not open a device");settle();homelabPreviewShow(11);homelabPreviewScroll(0);settle();tapButton(s.gpus[0].name);expect(homelabPreviewPage()==12,"deliberate GPU row tap opens telemetry detail");tapBack();expect(homelabPreviewPage()==11,"GPU detail returns to GPU list");tapBack();expect(homelabPreviewPage()==5,"GPU list returns to CPU detail");tapBack();expect(homelabPreviewPage()==0,"CPU GPU exploration returns to overview");
 nativeClock=(nativeClock/24000+1)*24000+18500;s.received=nativeClock;homelabPreviewShow(0);settle();tapButton(" GPUs",false);expect(homelabPreviewPage()==11,"overview GPU summary opens GPU list directly");tapBack();expect(homelabPreviewPage()==0,"GPU glance shortcut returns directly to overview");
 homelabPreviewGuest(s.guests[0].id);auto p=buttonPoint(s.gpus[0].name);point(p.x,p.y,true);point(p.x+20,p.y,true);point(p.x,p.y,true);point(p.x,p.y,false);expect(homelabPreviewPage()==4,"drag over assigned GPU button does not navigate");settle();tapButton(s.gpus[0].name);expect(homelabPreviewPage()==12,"assigned GPU deliberate tap opens its detail");
 String selectedName=s.gpus[0].name;std::swap(s.gpus[0],s.gpus[1]);homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),selectedName.c_str())!=nullptr,"selected GPU follows stable ID after inventory reorder");std::swap(s.gpus[0],s.gpus[1]);tapBack();expect(homelabPreviewPage()==4,"assigned GPU detail returns to original guest");
 double used=s.guests[0].used,total=s.guests[0].total;s.guests[0].used=s.guests[0].total=NAN;homelabPreviewShow(1);settle();expect(findText(lv_screen_active(),"Guest RAM unavailable")&&findText(lv_screen_active(),"-- / -- GiB"),"unavailable guest OS memory does not fall back to known PVE RAM");s.guests[0].used=used;s.guests[0].total=total;
 homelabPreviewShow(1);settle();expect(findText(lv_screen_active(),"OS/apps ~")!=nullptr,"NAS guest row identifies OS/apps estimate separately from ARC");homelabPreviewGuest(s.guests[1].id);settle();expect(findText(lv_screen_active(),"Used incl. ARC")&&findText(lv_screen_active(),"ARC cache")&&findText(lv_screen_active(),"OS/apps ~ estimate"),"NAS detail retains raw guest used, ARC and explicit OS/apps estimate");
 homelabPreviewShow(0);homelabPreviewTheme(false);screenshot((output/"dark-overview.ppm").string().c_str());
 homelabPreviewTheme(true);screenshot((output/"white-overview.ppm").string().c_str());
 // The production pure helpers also serve network restore/publication guards.
 char maximumId[65];memset(maximumId,'a',63);maximumId[63]=0;expect(validNodeId(maximumId),"63-byte feed node ID is accepted");maximumId[63]='a';maximumId[64]=0;expect(!validNodeId(maximumId)&&!validNodeId("bad?node")&&!validNodeId(""),"overlong and unsafe node IDs are rejected");char encoded[192];expect(encodeNodeId("test:printer",encoded,sizeof(encoded))&&!strcmp(encoded,"test%3Aprinter"),"node query identifier is URL encoded");expect(!encodeNodeId("test:printer",encoded,4),"undersized query encoding buffer is rejected");
 expect(nodeIndexForId(s,"test:printer")==1&&nodeIndexForId(s,"missing:node")==-1&&nodeIndexForId(s,"invalid node")==-1,"saved missing or invalid selection resolves to default registry fallback");
 static Snapshot reply;reply=s;expect(nodeReplyMatches(reply,"test:pve",4,4),"matching node generation can publish");expect(!nodeReplyMatches(reply,"test:pve",3,4)&&!nodeReplyMatches(reply,"test:printer",4,4),"late old-generation and wrong-node replies cannot publish");
 homelabPreviewShow(0);settle();tapButton("Test lab");expect(homelabPreviewPage()==13,"header node name opens configured-node picker");
 point(110,155,true);point(160,155,true);point(110,155,true);point(110,155,false);expect(homelabPreviewPage()==13&&!strcmp(s.node.id,"test:pve"),"horizontal node-row drag does not switch nodes");settle();
 homelabPreviewShow(13);homelabPreviewScroll(0);settle();point(110,150,true);point(110,120,true);point(110,85,true);point(110,85,false);expect(homelabPreviewPage()==13&&!strcmp(s.node.id,"test:pve"),"vertical node-row swipe does not switch nodes");settle();
 homelabPreviewShow(13);homelabPreviewScroll(0);settle();tapButton("Test printer");expect(homelabPreviewPage()==0&&!s.valid&&networkState.loading&&!strcmp(s.node.id,"test:printer"),"node tap selects printer and returns to loading home");expect(!s.nGuests&&!s.nDisks&&!s.nGpus&&!s.nSensors&&!isfinite(s.cpu)&&!isfinite(s.memUsed)&&homelabPreviewHistoryCount()==0,"node selection clears old metrics and CPU/RAM history");expect(findText(lv_screen_active(),"LOADING NODE")&&!findText(lv_screen_active(),"MEMORY",true),"loading printer never displays old Proxmox metric cards");screenshot((output/"printer-loading.ppm").string().c_str());
 loadPrinterFixture(s,networkState);s.generated=time(nullptr);s.received=nativeClock;homelabPreviewPoll();settle();expect(homelabPreviewPage()==0&&findText(lv_screen_active(),"65.5%")&&findText(lv_screen_active(),"220.0"),"selected printer reply renders progress and heater temperatures");screenshot((output/"printer-overview.ppm").string().c_str());
 dragReturning(buttonPoint("65.5%"),40);expect(homelabPreviewPage()==0,"drag over printer job hero does not navigate");settle();tapButton("65.5%");expect(homelabPreviewPage()==1,"printer progress hero deliberately opens job detail");expect(findText(lv_screen_active(),"-- / --",true)&&findText(lv_screen_active(),"Est. finish (UTC)"),"printer layers remain unknown and finish clock is explicitly UTC");
 tapTab(2);expect(homelabPreviewPage()==2,"printer Temps bottom tab opens thermal page");expect(findText(lv_screen_active(),"Duty 37.5%")&&findText(lv_screen_active(),"MCU temperature")&&findText(lv_screen_active(),"Raspberry Pi"),"printer thermal view retains heater duty percent and MCU/RPi sensors");
 tapTab(3);expect(homelabPreviewPage()==3,"printer Health bottom tab opens isolated health page");expect(!findText(lv_screen_active(),"Segfault")&&!findText(lv_screen_active(),"FAULT HISTORY"),"printer health excludes Proxmox fault inventory");
 s.printer.age=25;s.printer.ttl=90;s.received=nativeClock;s.generated=time(nullptr);homelabPreviewShow(0);settle();expect(findText(lv_screen_active(),"65.5%")&&findText(lv_screen_active(),"220.0"),"printer age25 remains visible under configured TTL90");
 s.printer.age=91;s.received=nativeClock;s.generated=time(nullptr);homelabPreviewShow(0);settle();expect(!findText(lv_screen_active(),"65.5%")&&!findText(lv_screen_active(),"220.0")&&findText(lv_screen_active(),"Stale printer data"),"printer age91 beyond TTL90 masks progress and thermal values");screenshot((output/"printer-stale.ppm").string().c_str());
 s.printer.age=1;s.received=nativeClock;strlcpy(s.printer.state,"paused",sizeof(s.printer.state));homelabPreviewShow(0);settle();expect(findText(lv_screen_active(),"Paused",true)&&!findText(lv_screen_active(),"30m",true),"paused print does not show an advancing finish estimate");
 strlcpy(s.printer.klippyState,"startup",sizeof(s.printer.klippyState));homelabPreviewShow(0);settle();expect(findText(lv_screen_active(),"Starting",true),"Klipper startup has a distinct state");strlcpy(s.printer.klippyState,"shutdown",sizeof(s.printer.klippyState));homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),"Klipper shutdown",true),"Klipper shutdown has a distinct state");strlcpy(s.printer.klippyState,"disconnected",sizeof(s.printer.klippyState));homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),"Disconnected",true),"Klipper disconnected has a distinct state");
 strlcpy(s.printer.klippyState,"ready",sizeof(s.printer.klippyState));strlcpy(s.node.status,"offline",sizeof(s.node.status));homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),"Offline",true),"offline printer has a distinct state");
 strlcpy(s.node.status,"healthy",sizeof(s.node.status));strlcpy(s.printer.state,"printing",sizeof(s.printer.state));s.received=nativeClock;s.generated=time(nullptr);homelabPreviewShow(0);homelabPreviewTheme(false);screenshot((output/"dark-printer-overview.ppm").string().c_str());homelabPreviewTheme(true);tapButton(s.node.name);tapButton("Test lab");expect(!s.valid&&!strcmp(s.node.id,"test:pve")&&!s.printer.present,"switching back to Proxmox clears printer data");
 tapButton(LV_SYMBOL_SETTINGS);tapButton("Nodes & monitoring");expect(homelabPreviewPage()==15&&findText(lv_screen_active(),"Test printer",true),"Settings opens configuration-sourced node management");screenshot((output/"nodes-management.ppm").string().c_str());
 auto managed=buttonPoint("Test printer");point(managed.x,managed.y,true);point(managed.x+25,managed.y,true);point(managed.x,managed.y,true);point(managed.x,managed.y,false);expect(homelabPreviewPage()==15&&!nativeUpserts&&!nativeDeletes,"drag over management row does not edit or write");settle();tapButton("Test printer");expect(homelabPreviewPage()==16,"node management tap opens editable form");screenshot((output/"node-edit.ppm").string().c_str());tapButton("Node name");expect(homelabPreviewPage()==18&&findClass(lv_screen_active(),&lv_keyboard_class),"node field opens real software keyboard");
 auto*area=findClass(lv_screen_active(),&lv_textarea_class);String beforeName=lv_textarea_get_text(area);dragReturning(keyboardPoint("q"),40);settle();expect(String(lv_textarea_get_text(area))==beforeName,"keyboard drag does not enter accidental characters");tapKey("q");screenshot((output/"keyboard-node-name.ppm").string().c_str());expect(String(lv_textarea_get_text(area))==beforeName+"q","deliberate keyboard tap enters a character on release");tapKey(LV_SYMBOL_OK);expect(homelabPreviewPage()==16,"keyboard accept returns to retained node draft");tapButton("Save node");expect(nativeUpserts==1&&homelabPreviewPage()==15&&findText(lv_screen_active(),"Test printerq",true),"node save queues a configuration write and shows returned identity");
 tapButton("Test printerq");tapButton("Remove node");expect(homelabPreviewPage()==17&&!nativeDeletes,"Remove opens deliberate confirmation without deleting");screenshot((output/"node-delete-confirmation.ppm").string().c_str());tapButton("Keep node");expect(homelabPreviewPage()==16&&!nativeDeletes,"delete cancellation preserves configured node");tapButton("Remove node");auto remove=buttonPoint("Remove this node");point(remove.x,remove.y,true);point(remove.x+25,remove.y,true);point(remove.x,remove.y,true);point(remove.x,remove.y,false);expect(!nativeDeletes&&homelabPreviewPage()==17,"drag over delete confirmation cannot remove node");settle();tapButton("Remove this node");expect(nativeDeletes==1&&homelabPreviewPage()==15&&nativeConfiguration.count==1,"deliberate delete confirmation removes only monitor configuration");
 tapButton("+ Add polling feed");expect(homelabPreviewPage()==16&&findText(lv_screen_active(),"Klipper",true),"Add opens typed node form with sensible sampling defaults");tapButton("Klipper");tapButton("Node name");area=findClass(lv_screen_active(),&lv_textarea_class);lv_textarea_set_text(area,"New test printer");tapKey(LV_SYMBOL_OK);tapButton("Service URL");area=findClass(lv_screen_active(),&lv_textarea_class);lv_textarea_set_text(area,"http://printer.test:7125");tapKey(LV_SYMBOL_OK);tapButton("Save node");expect(nativeUpserts==2&&nativeConfiguration.count==2&&homelabPreviewPage()==15,"new named printer with optional generated ID can be saved");
 tapButton(LV_SYMBOL_SETTINGS);tapButton("Wi-Fi & collector setup");expect(homelabPreviewPage()==14&&findText(lv_screen_active(),"Test desk Wi-Fi",true),"Settings opens touch-native Wi-Fi configuration");screenshot((output/"wifi-form-overview.ppm").string().c_str());tapButton("Wi-Fi password");area=findClass(lv_screen_active(),&lv_textarea_class);expect(homelabPreviewPage()==18&&lv_textarea_get_password_mode(area)&&!strlen(lv_textarea_get_text(area)),"saved Wi-Fi password is never read back and editor is masked");lv_textarea_set_text(area,"synthetic-password");tapBack();expect(homelabPreviewPage()==14&&!findText(lv_screen_active(),"new password"),"keyboard Back cancels secret draft without replacing saved password");
 tapButton("Save & connect");expect(nativeConnectionSaves==1&&nativeConnection.passwordSaved&&nativeConnection.displayTokenSaved&&nativeConnection.setupTokenSaved,"blank same-endpoint Wi-Fi save retains existing secret flags");screenshot((output/"wifi-form.ppm").string().c_str());
 tapButton("Display token");area=findClass(lv_screen_active(),&lv_textarea_class);expect(lv_textarea_get_password_mode(area)&&!strlen(lv_textarea_get_text(area)),"saved display token is masked and never returned to editor");tapBack();tapButton("Setup token");area=findClass(lv_screen_active(),&lv_textarea_class);expect(lv_textarea_get_password_mode(area)&&!strlen(lv_textarea_get_text(area)),"separate setup token is masked and never returned to editor");screenshot((output/"setup-token-editor.ppm").string().c_str());tapBack();
 tapButton("Wi-Fi password");area=findClass(lv_screen_active(),&lv_textarea_class);lv_textarea_set_text(area,"synthetic-new-password");tapKey(LV_SYMBOL_OK);nativeFailConnection=true;tapButton("Save & connect");expect(homelabPreviewPage()==14&&findText(lv_screen_active(),"new password"),"failed Wi-Fi save retains masked entered password draft");nativeFailConnection=false;tapButton("Save & connect");expect(!findText(lv_screen_active(),"new password"),"verified Wi-Fi save clears entered secret draft");
 tapButton(LV_SYMBOL_SETTINGS);tapButton("Nodes & monitoring");tapButton("New test printer");tapButton("Service token");area=findClass(lv_screen_active(),&lv_textarea_class);lv_textarea_set_text(area,"synthetic-service-token");tapKey(LV_SYMBOL_OK);nativeFailUpsert=true;tapButton("Save node");expect(homelabPreviewPage()==16&&!nativeConfiguration.applying&&findText(lv_screen_active(),"new service token"),"failed second node save cannot inherit success and retains masked token draft");nativeFailUpsert=false;nativeResumeBeforeUi=true;tapButton("Save node");expect(homelabPreviewPage()==15&&nativeUpserts==3,"retained node draft can be retried after validation failure");expect(nativeConfiguration.saved&&!nativeConfiguration.applying&&!findText(lv_screen_active(),"new service token"),"feed resuming before UI poll still acknowledges save and clears masked draft");NodeConfiguration settling;settling.applying=settling.saved=true;expect(settleNodeConfiguration(settling)&&!settling.applying&&settling.saved&&strstr(settling.message,"Monitoring resumed"),"resumed monitoring settles applying without losing saved outcome");settling.busy=settling.applying=true;expect(!settleNodeConfiguration(settling)&&settling.applying,"active configuration request cannot be settled by unrelated live reply");

 // Generic devices reuse standard telemetry while omitting Proxmox-only pages.
 new(&s)Snapshot{};s.valid=true;s.demo=true;s.generated=time(nullptr);s.received=nativeClock;s.sequence=5;networkState.loading=false;
 strlcpy(s.node.id,"test:device",sizeof(s.node.id));strlcpy(s.node.type,"server",sizeof(s.node.type));strlcpy(s.node.platform,"macos",sizeof(s.node.platform));strlcpy(s.node.name,"Test Mac",sizeof(s.node.name));strlcpy(s.node.status,"healthy",sizeof(s.node.status));
 strlcpy(s.osRelease,"Test OS release",sizeof(s.osRelease));strlcpy(s.architecture,"arm64",sizeof(s.architecture));s.cpuCount=8;s.batteryPercent=78;s.batteryPlugged=1;s.nInterfaces=1;strlcpy(s.interfaces[0].name,"LAN",sizeof(s.interfaces[0].name));strlcpy(s.interfaces[0].status,"up",sizeof(s.interfaces[0].status));s.interfaces[0].speed=1000;s.interfaces[0].rx=1500000;s.interfaces[0].tx=210000;s.interfaces[0].errorsIn=0;s.interfaces[0].errorsOut=2;
 s.nodes[0]=s.node;s.nNodes=1;s.nSensors=1;strlcpy(s.sensors[0].name,"Board thermal",sizeof(s.sensors[0].name));strlcpy(s.sensors[0].kind,"temperature",sizeof(s.sensors[0].kind));strlcpy(s.sensors[0].unit,"°C",sizeof(s.sensors[0].unit));s.sensors[0].value=43.7;
 homelabPreviewPoll();homelabPreviewShow(0);settle();expect(findText(lv_screen_active(),"Health",true)&&!findText(lv_screen_active(),"Guests",true)&&findText(lv_screen_active(),"--",true),"generic device tabs exclude Guests and unknown CPU/RAM stay explicit");screenshot((output/"generic-device-overview.ppm").string().c_str());
 tapTab(1);expect(homelabPreviewPage()==2&&findText(lv_screen_active(),"Filesystems & disks",true),"generic Storage tab reaches filesystem inventory");tapTab(2);expect(homelabPreviewPage()==3&&findText(lv_screen_active(),"Board thermal",true),"generic Sensors tab renders device thermal readings");tapTab(3);expect(homelabPreviewPage()==6&&findText(lv_screen_active(),"macOS",true)&&!findText(lv_screen_active(),"PROXMOX FAULTS")&&!findText(lv_screen_active(),"Segfaults",true),"generic Health identifies macOS without unsupported Proxmox fault rows");
 expect(findText(lv_screen_active(),"Test OS release")&&findText(lv_screen_active(),"arm64",true)&&findText(lv_screen_active(),"78%",true)&&findText(lv_screen_active(),"LAN",true)&&findText(lv_screen_active(),"RX 1.5 MB/s")&&findText(lv_screen_active(),"Errors in/out: 0 / 2"),"generic Health retains OS architecture, battery and per-interface counters");homelabPreviewScroll(100000);settle();screenshot((output/"generic-device-interfaces.ppm").string().c_str());homelabPreviewScroll(0);
 for(const char*platform:{"linux","windows","router","other"}){strlcpy(s.node.platform,platform,sizeof(s.node.platform));homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),platformName(platform),true),"generic Health retains Linux, Windows, router and other platform identity");}screenshot((output/"generic-device-health.ppm").string().c_str());
 s.nodes[0]=s.node;homelabPreviewShow(13);settle();expect(findText(lv_screen_active(),"Other device"),"generic node picker shows device platform");tapTab(0);expect(homelabPreviewPage()==0,"generic Overview tab returns home");tapButton("CPU");expect(homelabPreviewPage()==5,"generic CPU card opens standard power details");tapBack();expect(homelabPreviewPage()==0,"generic CPU Back preserves originating overview");
 tapButton(LV_SYMBOL_SETTINGS);tapButton("Nodes & monitoring");tapButton("+ Add polling feed");tapButton("Device feed");expect(findText(lv_screen_active(),"Platform: Auto from device"),"generic feed setup exposes platform auto detection");tapButton("Platform: Auto from device",false);tapButton("Platform: Linux",false);expect(findText(lv_screen_active(),"Platform: macOS"),"generic feed setup cycles to macOS platform");tapButton("Node name");area=findClass(lv_screen_active(),&lv_textarea_class);lv_textarea_set_text(area,"New Mac");tapKey(LV_SYMBOL_OK);tapButton("Service URL");area=findClass(lv_screen_active(),&lv_textarea_class);lv_textarea_set_text(area,"http://mac.test:8765/api/v1/snapshot");tapKey(LV_SYMBOL_OK);tapButton("Save node");expect(nativeConfiguration.count==3&&!strcmp(nativeConfiguration.nodes[2].type,"server-feed")&&!strcmp(nativeConfiguration.nodes[2].platform,"macos"),"generic feed save retains type and selected platform");

 tapButton("Test lab");tapButton("Server");expect(findText(lv_screen_active(),"Platform: Linux")&&!findText(lv_screen_active(),"Auto from device")&&!findText(lv_screen_active(),"macOS",true),"local mode selector fixes the native host platform to Linux");screenshot((output/"local-server-mode.ppm").string().c_str());tapButton("Save node");expect(nativeConfiguration.count==3&&!strcmp(nativeConfiguration.nodes[0].type,"local-server")&&!strcmp(nativeConfiguration.nodes[0].id,"test:pve")&&!strcmp(nativeConfiguration.nodes[0].platform,"linux"),"local Proxmox can switch to Linux server while retaining its stable ID");
 tapButton("Test lab");tapButton("Proxmox");tapButton("Save node");expect(nativeConfiguration.count==3&&!strcmp(nativeConfiguration.nodes[0].type,"local-proxmox")&&!strcmp(nativeConfiguration.nodes[0].id,"test:pve"),"local Linux server can switch back to Proxmox without adding a node");
 tapButton("Test lab");tapButton("Remove node");tapButton("Remove this node");tapButton("+ Add polling feed");tapButton("Hub host");tapButton("Server");tapButton("Save node");expect(nativeConfiguration.count==3&&!strcmp(nativeConfiguration.nodes[2].type,"local-server")&&!strcmp(nativeConfiguration.nodes[2].id,"test:pve")&&!strcmp(nativeConfiguration.nodes[2].platform,"linux"),"restoring the local node allows Linux server mode and retains its fixed ID");

 strlcpy(nativeConfiguration.localPlatform,"macos",sizeof(nativeConfiguration.localPlatform));strlcpy(nativeConfiguration.nodes[2].platform,"macos",sizeof(nativeConfiguration.nodes[2].platform));strlcpy(nativeConfiguration.nodes[2].type,"local-server",sizeof(nativeConfiguration.nodes[2].type));homelabPreviewShow(15);tapButton("Test lab");expect(findText(lv_screen_active(),"Platform: macOS")&&!findText(lv_screen_active(),"Platform: Linux"),"collector host editor reflects native macOS instead of assuming Linux");tapButton("Proxmox");expect(findText(lv_screen_active(),"Proxmox collection requires a Linux host."),"non-Linux host cannot switch to Proxmox collection");tapButton("Server");tapButton("Save node");expect(!strcmp(nativeConfiguration.nodes[2].platform,"macos")&&!strcmp(nativeConfiguration.nodes[2].type,"local-server"),"native macOS host save preserves its actual platform");screenshot((output/"native-macos-host-mode.ppm").string().c_str());

 // The fleet summary uses a bounded card per node, with independent freshness.
 new(&s)Snapshot{};s.valid=true;s.generated=time(nullptr);s.received=nativeClock;s.sequence=10;networkState.wifi=networkState.configured=true;networkState.loading=false;s.nNodes=4;
 const char*summaryNames[]={"Summary host","Summary printer","Summary Mac","Summary router"};const char*summaryIds[]={"summary:host","summary:printer","summary:mac","summary:router"};
 for(int i=0;i<4;i++){auto&n=s.nodes[i];strlcpy(n.name,summaryNames[i],sizeof(n.name));strlcpy(n.id,summaryIds[i],sizeof(n.id));strlcpy(n.type,i==0?"proxmox":i==1?"klipper":"server",sizeof(n.type));strlcpy(n.platform,i==2?"macos":i==3?"router":"linux",sizeof(n.platform));strlcpy(n.status,"healthy",sizeof(n.status));auto&v=n.summary;v.available=true;v.cpu=i==2?0:12+i;v.memory=53+i;v.temp=42+i;v.age=0;v.generated=time(nullptr);v.ttl=15;v.sensors=23;v.guests=3;v.progress=65;strlcpy(v.printState,"printing",sizeof(v.printState));strlcpy(v.status,"healthy",sizeof(v.status));}
 s.node=s.nodes[0];homelabPreviewShow(19);settle();expect(findText(lv_screen_active(),"4 / 4 healthy",true)&&findText(lv_screen_active(),"CPU 0%")&&findText(lv_screen_active(),"printing 65%",true)&&findText(lv_screen_active(),"3 guests"),"bento overview preserves zero, printer progress and Proxmox guest summaries");expect(contentLabelsClearTabs(lv_obj_get_parent(lv_obj_get_parent(findText(lv_screen_active(),"Summary router",true)))),"all four bento cards fit above the bottom tabs");screenshot((output/"all-nodes-overview.ppm").string().c_str());homelabPreviewTheme(false);screenshot((output/"dark-all-nodes-overview.ppm").string().c_str());homelabPreviewTheme(true);
 auto cardPoint=buttonPoint("Summary printer");dragReturning(cardPoint,25);expect(homelabPreviewPage()==19&&!strcmp(s.node.id,"summary:host"),"bento card drag does not select a node");settle();tapButton("Summary printer");expect(homelabPreviewPage()==0&&!s.valid&&!strcmp(s.node.id,"summary:printer")&&networkState.loading,"bento card tap selects stable node identity and opens its dashboard");
 s.valid=true;s.received=nativeClock;networkState.loading=false;s.nodes[1].summary.age=16;s.nodes[2].summary.cpu=NAN;strlcpy(s.nodes[3].status,"offline",sizeof(s.nodes[3].status));strlcpy(s.nodes[3].summary.status,"offline",sizeof(s.nodes[3].summary.status));homelabPreviewShow(19);settle();expect(findText(lv_screen_active(),"2 / 4 healthy",true)&&findText(lv_screen_active(),"Klipper • Stale",true)&&findText(lv_screen_active(),"Router • Offline",true)&&!findText(lv_screen_active(),"printing 65%",true)&&findText(lv_screen_active(),"CPU --"),"stale and offline cards mask measurements independently while unknown CPU stays unknown");screenshot((output/"all-nodes-freshness.ppm").string().c_str());
 tapTab(2);expect(homelabPreviewPage()==13&&findText(lv_screen_active(),"All nodes • summary",true),"fleet Pick node tab reaches the summary-aware picker");tapButton("All nodes • summary");expect(homelabPreviewPage()==19,"picker summary entry returns to fleet view");tapTab(1);expect(homelabPreviewPage()==0,"fleet Selected tab opens the selected node dashboard");tap(24,12);expect(homelabPreviewPage()==19,"brand home returns to all-node overview");tapTab(3);expect(homelabPreviewPage()==7,"fleet Settings tab opens settings");tap(24,12);expect(homelabPreviewPage()==19,"Settings brand home returns to fleet overview");
 nativeClock+=16000;homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),"0 / 4 healthy",true)&&!findText(lv_screen_active(),"CPU 12%"),"collector receipt expiry masks every summary card");screenshot((output/"all-nodes-collector-stale.ppm").string().c_str());s.nNodes=0;s.valid=false;homelabPreviewRefresh();settle();expect(findText(lv_screen_active(),"Manage collector nodes",true)&&!findText(lv_screen_active(),"Summary host",true),"empty collector has a node-management entry without fabricated cards");
 s.valid=false;networkState.loading=false;networkState.wifi=true;
 strlcpy(networkState.message,"Collector connection timed out. Check the server address, display token and Wi-Fi and try again",sizeof(networkState.message));
 homelabPreviewPoll();homelabPreviewShow(0);homelabPreviewScroll(0);settle();
 auto*waiting=findText(lv_screen_active(),"WAITING FOR COLLECTOR",true);auto*error=findText(lv_screen_active(),networkState.message,true);auto*setup=findText(lv_screen_active(),"Wi-Fi & collector setup",true);
 expect(waiting&&lv_label_get_long_mode(waiting)==LV_LABEL_LONG_WRAP,"offline heading wraps without truncating collector state");
 lv_obj_update_layout(lv_screen_active());lv_area_t headingBounds,messageBounds,setupBounds;lv_obj_get_coords(waiting,&headingBounds);lv_obj_get_coords(error,&messageBounds);lv_obj_get_coords(lv_obj_get_parent(setup),&setupBounds);
 expect(headingBounds.y2<messageBounds.y1&&messageBounds.y2<setupBounds.y1,"95-byte offline message cannot overlap heading or setup action");screenshot((output/"offline-long-message.ppm").string().c_str());
 auto recovery=buttonPoint("Wi-Fi & collector setup");expect(recovery.y>=headerHeight&&recovery.y<height-40,"offline setup action scrolls into the content viewport");screenshot((output/"offline-long-message-end.ppm").string().c_str());tap(recovery.x,recovery.y);expect(homelabPreviewPage()==14,"offline setup action still opens connection form after long error");
 printf("All continuous-pointer integration checks passed.\n");
}
