#pragma once
// Native-only simulated settings adapter. It never contacts an endpoint or NVS.
#include "model.h"
inline ConnectionSettings nativeConnection;
inline NodeConfiguration nativeConfiguration;
inline uint32_t nativeUpserts=0,nativeDeletes=0,nativeConnectionSaves=0;inline bool nativeFailConnection=false,nativeFailUpsert=false,nativeResumeBeforeUi=false;
inline void nativeManagementInit(){
 if(!nativeConnection.available){nativeConnection.available=true;strlcpy(nativeConnection.ssid,"Test desk Wi-Fi",sizeof(nativeConnection.ssid));strlcpy(nativeConnection.endpoint,"http://collector.test:8765/api/v1/snapshot",sizeof(nativeConnection.endpoint));nativeConnection.passwordSaved=nativeConnection.displayTokenSaved=nativeConnection.setupTokenSaved=true;strlcpy(nativeConnection.message,"Native preview: Wi-Fi changes simulated.",sizeof(nativeConnection.message));}
 if(!nativeConfiguration.available)loadConfigurationFixture(nativeConfiguration);
 if(!nativeConfiguration.available&&publishedSnapshot){nativeConfiguration.available=true;memset(nativeConfiguration.version,'a',64);nativeConfiguration.version[64]=0;for(int i=0;i<publishedSnapshot->nNodes&&i<int(MAX_NODES);i++){auto&from=publishedSnapshot->nodes[i];auto&n=nativeConfiguration.nodes[nativeConfiguration.count++];strlcpy(n.id,from.id,sizeof(n.id));strlcpy(n.name,from.name,sizeof(n.name));bool local=!strcmp(from.type,"proxmox")&&!nativeConfiguration.localId[0];strlcpy(n.type,local?"local-proxmox":!strcmp(from.type,"klipper")?"klipper":"proxmox-feed",sizeof(n.type));strlcpy(n.origin,local?"local":"config",sizeof(n.origin));if(local){strlcpy(nativeConfiguration.localId,n.id,sizeof(nativeConfiguration.localId));strlcpy(nativeConfiguration.localName,n.name,sizeof(nativeConfiguration.localName));strlcpy(nativeConfiguration.localAddress,from.address,sizeof(nativeConfiguration.localAddress));nativeConfiguration.localEnabled=true;}else{String url=String("http://")+from.address+(!strcmp(from.type,"klipper")?"":"/api/v1/snapshot");strlcpy(n.url,url.c_str(),sizeof(n.url));}}}
}
bool readConnectionSettings(ConnectionSettings&out){nativeManagementInit();out=nativeConnection;return true;}
bool requestConnectionUpdate(const ConnectionUpdate&u){nativeManagementInit();nativeConnection.saved=false;if(nativeFailConnection||!u.ssid[0]||!u.endpoint[0]){strlcpy(nativeConnection.message,"Enter Wi-Fi name and collector URL.",sizeof(nativeConnection.message));nativeConnection.revision++;return true;}nativeConnectionSaves++;nativeConnection.saved=true;strlcpy(nativeConnection.ssid,u.ssid,sizeof(nativeConnection.ssid));bool same=!strcmp(nativeConnection.endpoint,u.endpoint);strlcpy(nativeConnection.endpoint,u.endpoint,sizeof(nativeConnection.endpoint));nativeConnection.passwordSaved=!u.clearPassword&&(u.password[0]||nativeConnection.passwordSaved);nativeConnection.displayTokenSaved=u.displayToken[0]||(same&&nativeConnection.displayTokenSaved);nativeConnection.setupTokenSaved=u.setupToken[0]||(same&&nativeConnection.setupTokenSaved);strlcpy(nativeConnection.message,"Native preview: save simulated.",sizeof(nativeConnection.message));nativeConnection.revision++;return true;}
bool readNodeConfiguration(NodeConfiguration&out){nativeManagementInit();out=nativeConfiguration;return true;}
bool requestNodeConfiguration(){nativeManagementInit();nativeConfiguration.revision++;nativeConfiguration.applying=false;nativeConfiguration.saved=false;nativeConfiguration.message[0]=0;return true;}
bool requestNodeUpsert(const NodeConfigDraft&draft,const char*version){nativeManagementInit();nativeConfiguration.applying=false;nativeConfiguration.saved=false;if(nativeFailUpsert){strlcpy(nativeConfiguration.message,"Native preview: validation rejected.",sizeof(nativeConfiguration.message));nativeConfiguration.revision++;return true;}if(strcmp(version,nativeConfiguration.version))return false;int index=-1;for(int i=0;i<nativeConfiguration.count;i++)if(draft.node.id[0]&&!strcmp(draft.node.id,nativeConfiguration.nodes[i].id))index=i;if(index<0){if(nativeConfiguration.count>=MAX_NODES)return false;index=nativeConfiguration.count++;}auto&n=nativeConfiguration.nodes[index];n=draft.node;if(!n.id[0])snprintf(n.id,sizeof(n.id),"test:new-%u",unsigned(index));n.hasSecret=draft.secret[0]||(!draft.clearSecret&&n.hasSecret);nativeUpserts++;nativeConfiguration.applying=true;nativeConfiguration.saved=true;strlcpy(nativeConfiguration.message,"Native preview: node save simulated.",sizeof(nativeConfiguration.message));nativeConfiguration.revision++;if(nativeResumeBeforeUi)settleNodeConfiguration(nativeConfiguration);return true;}
bool requestNodeDelete(const char*id,const char*version){nativeManagementInit();if(strcmp(version,nativeConfiguration.version))return false;for(int i=0;i<nativeConfiguration.count;i++)if(!strcmp(id,nativeConfiguration.nodes[i].id)){for(int j=i+1;j<nativeConfiguration.count;j++)nativeConfiguration.nodes[j-1]=nativeConfiguration.nodes[j];nativeConfiguration.count--;nativeDeletes++;nativeConfiguration.applying=true;nativeConfiguration.saved=true;strlcpy(nativeConfiguration.message,"Native preview: deletion simulated.",sizeof(nativeConfiguration.message));nativeConfiguration.revision++;return true;}return false;}
