import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {validateFlashManifest,verifiedImages,programVerifiedImages} from '../src/flash-plan.js';

const bytes=new Uint8Array([1,2,3]);
const digest=data=>createHash('sha256').update(data).digest('hex');
const bundle=()=>({schema:1,chip:'ESP32-S3',board:'waveshare-v1',rotation:3,flash_size:0x1000000,parts:[0,0x8000,0xe000,0x10000].map((offset,index)=>({offset,size:3,path:`/firmware/${index}.bin`,sha256:digest(bytes)}))});
const origin='http://localhost:8766';
test('known segment layout excludes rounded NVS erase range',()=>{assert.equal(validateFlashManifest(bundle(),origin).length,4);for(const [offset,size] of [[0x8000,4097],[0x9000,3],[0,0x9000]]){const m=bundle();m.parts[1]={...m.parts[1],offset,size};assert.throws(()=>validateFlashManifest(m,origin));}});
test('cross-origin files, duplicate segments and incompatible hardware are rejected',()=>{for(const mutate of [m=>m.parts[0].path='https://other.example/firmware/a.bin',m=>m.parts[1].offset=0,m=>m.chip='ESP32',m=>m.rotation=0,m=>m.parts[0].sha256='x']){const m=bundle();mutate(m);assert.throws(()=>validateFlashManifest(m,origin));}});
test('all firmware files are checked before programming',async()=>{const images=await verifiedImages(bundle(),{origin,fetchFile:async()=>bytes,sha256:digest});assert.equal(images.length,4);await assert.rejects(verifiedImages(bundle(),{origin,fetchFile:async()=>new Uint8Array([4,5,6]),sha256:digest}),/SHA-256/);await assert.rejects(verifiedImages(bundle(),{origin,fetchFile:async()=>new Uint8Array(2),sha256:digest}),/size/);});
function device(overrides={}){const events=[];return {events,chip:{CHIP_NAME:'ESP32-S3'},secureDownloadMode:false,getSecurityInfo:async()=>({parsedFlags:{},flashCryptCnt:0}),readReg:async address=>[0x60004004,0x60004020,0x6000403c].includes(address)?0x80:0,writeReg:async()=>{events.push('gpio');},runStub:async()=>{events.push('stub');},detectFlashSize:async()=>'16MB',flashSizeBytes:()=>0x1000000,writeFlash:async options=>{events.push(options);options.reportProgress(0,3,3);},after:async mode=>{events.push(mode);},...overrides};}
test('verified updater writes only checked segments, verifies MD5 and never erases all flash',async()=>{const loader=device(),progress=[];const images=await verifiedImages(bundle(),{origin,fetchFile:async()=>bytes,sha256:digest});await programVerifiedImages(loader,images,{md5:()=> 'known-md5',onProgress:n=>progress.push(n)});const flash=loader.events.find(event=>event.fileArray);assert.equal(flash.eraseAll,false);assert.equal(flash.calculateMD5Hash(bytes),'known-md5');assert.deepEqual(flash.fileArray.map(image=>image.address),[0,0x8000,0xe000,0x10000]);assert.equal(loader.events.at(-1),'hard_reset');assert.equal(progress.at(-1),100);assert(loader.events.indexOf('gpio')<loader.events.indexOf('stub'));});
test('wrong chip, flash encryption, latch failure, small flash and verification errors stop before reset',async()=>{for(const loader of [device({chip:{CHIP_NAME:'ESP32'}}),device({getSecurityInfo:async()=>({parsedFlags:{SECURE_BOOT_EN:true},flashCryptCnt:0})}),device({getSecurityInfo:async()=>({parsedFlags:{},flashCryptCnt:1})}),device({readReg:async()=>0}),device({flashSizeBytes:()=>0x800000}),device({writeFlash:async()=>{throw Error('MD5 mismatch');}})]){await assert.rejects(programVerifiedImages(loader,[{address:0x10000,data:bytes}],{md5:()=>''}));assert(!loader.events.includes('hard_reset'));}});
